AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - AWS::SecretsManager-2020-07-23
Description: >-
    Creates an Aurora Serverless (MySql) database and uses a CFN Custom Resource to initialize it with a schema.
    Also uses SecretsManager to store the admin credentials - and rotate them every 30 days

Parameters:
    
  Subnets:
    Description: Choose Subnets for the RDSCluster. Must be Private subnets with NAT GW, or S3 Gateway for access to S3 (for CustomResource schema setup)
    Type: String

  APIKeySecretArn:
    Type: String
    Default: "arn:aws:secretmanager:REGION:ACCOUNTID:secret:SECRETNAME"
    Description: "Enter the ARN of the Secrets Manager Secret that holds the OpenWeatherMap API Key (You must create this yourself!)"

Resources:

  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: Subnet group for Aurora Serverless
      SubnetIds: !Split [',', !Ref Subnets]
  
  DBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Secret for the database user and password
      # Auto-generate a 30 character password for a user named "weatheradmin"
      GenerateSecretString:
        SecretStringTemplate: '{"username":"weatheradmin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true
        
  DBSecretRotation:
    Type: 'AWS::SecretsManager::RotationSchedule'
    Properties:
      # This basically creates a lambda for us to do the rotation.
      HostedRotationLambda:
        # See here: https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html#sar-template-mysql-singleuser
        RotationType: MySQLSingleUser
        # We have to specify this because the Lambda will need to be connected to the VPC in order to change the password.
        # https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.py
        VpcSecurityGroupIds: !ImportValue 'pyweather-aurora-DBSecurityGroup'
        VpcSubnetIds: !Ref Subnets
      RotationRules:
        AutomaticallyAfterDays: 30
        Duration: 2h
        # For more precise control, consider using a cron expression.
        #ScheduleExpression: "cron(0 1 * * ? *)"
      SecretId: !Ref DBSecret
  
  SecretTargetAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    # We have to associate together the Secret and the RDS Cluster after they are created.
    # This causes the DB Connection info (host, port, etc.) to be injected into the Secret.
    # The rotation lambda depends on this being here!
    # I found that adding this explicit DependsOn is necessary.
    DependsOn: 
      - RDSCluster
      - DBSecret
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref RDSCluster
      TargetType: "AWS::RDS::DBCluster"

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      # NOTE: username and password are coming from the secret created earlier in this stack.
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ]]
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.02.0

      # NOTE: EngineMode serverless refers to V1 Serverless - Not V2!
      #https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.create-cluster.html
      #EngineMode: serverless
      ServerlessV2ScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 4
      
      # Not supported in Aurora Serverless V2
      # So we can use Data API / Query Editor in the console, if we want (Great for demos!)
      #EnableHttpEndpoint: true
      
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue 'pyweather-aurora-DBSecurityGroup'
  
  RDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora-mysql
      DBInstanceClass: db.serverless
      DBClusterIdentifier: !Ref RDSCluster
      
      
  CustomResource:
    Type: AWS::CloudFormation::CustomResource
    # Trigger a Lambda to create the db schema once the cluster AND INSTANCE is available.
    DependsOn: RDSDBInstance
    Properties:
      # Note that we're passing the RDS details needed by the lambda (endpoint and secret arn)
      RDSEndpoint: !GetAtt RDSCluster.Endpoint.Address
      RDSPort: !GetAtt RDSCluster.Endpoint.Port
      DBSecret: !Ref DBSecret
      ServiceToken: !Join 
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !ImportValue 'pyweather-aurora-LambdaForSchema'

  # Add a Resource Policy on the Secret so that LambdaForSchema can access it.
  # This Lambda was created in the first stack, but we didn't have the Secret defined at that time
  # So easiest thing to do is enable access via the RESOURCE POLICY on the SECRET (as opposed to the lambda execution role)
  DBSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId:
        Ref: DBSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Resource: "*"
          Action: secretsmanager:GetSecretValue
          Effect: Allow
          Principal:
            AWS: !ImportValue "pyweather-aurora-CustomResourceRoleArn"

  # This is the actual PyWeather function.
  PyWeatherAurora:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 90
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DBSecret
          RDS_ENDPOINT: !GetAtt RDSCluster.Endpoint.Address
      VpcConfig:
        SecurityGroupIds: 
          - !ImportValue "pyweather-aurora-DBSecurityGroup"
        SubnetIds: !Split [',', !Ref Subnets]
      Events:
        PyWeatherDemo:
          Type: Api 
          Properties:
            Path: /
            Method: get
            
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: FunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # These things needed for VPC access.
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: 
                  - !Ref APIKeySecretArn
                  - !Ref DBSecret